"""Basic tables

Revision ID: 0c27feea175b
Revises: e6ae69e9dcb9
Create Date: 2019-05-10 23:23:29.261563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c27feea175b'
down_revision = 'e6ae69e9dcb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filepath', sa.String(length=120), nullable=True),
    sa.Column('type', sa.Enum('AREA_GRAPH', 'BAR_GRAPH', 'BOX_PLOT', 'BUBBLE_CHART', 'COLUMN_GRAPH', 'LINE_GRAPH', 'PARETO_CHART', 'PIE_CHART', 'RADAR_PLOT', 'SCATTER_GRAPH', name='charttype'), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('x_axis_title', sa.String(length=200), nullable=True),
    sa.Column('y_axis_title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=4000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chart_description'), 'chart', ['description'], unique=False)
    op.create_index(op.f('ix_chart_id'), 'chart', ['id'], unique=False)
    op.create_index(op.f('ix_chart_title'), 'chart', ['title'], unique=False)
    op.create_index(op.f('ix_chart_type'), 'chart', ['type'], unique=False)
    op.create_index(op.f('ix_chart_x_axis_title'), 'chart', ['x_axis_title'], unique=False)
    op.create_index(op.f('ix_chart_y_axis_title'), 'chart', ['y_axis_title'], unique=False)
    op.create_table('survey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=4000), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='surveystatus'), nullable=True),
    sa.Column('type', sa.Enum('SINGLE', 'COMPARISON', name='surveytype'), nullable=True),
    sa.Column('researcher_id', sa.Integer(), nullable=True),
    sa.Column('answers_per_task', sa.Integer(), nullable=True),
    sa.Column('tasks_per_chart', sa.Integer(), nullable=True),
    sa.Column('exp_required', sa.Boolean(), nullable=True),
    sa.Column('min_answers_quality', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['researcher_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_id'), 'survey', ['id'], unique=False)
    op.create_index(op.f('ix_survey_name'), 'survey', ['name'], unique=False)
    op.create_index(op.f('ix_survey_researcher_id'), 'survey', ['researcher_id'], unique=False)
    op.create_index(op.f('ix_survey_status'), 'survey', ['status'], unique=False)
    op.create_index(op.f('ix_survey_type'), 'survey', ['type'], unique=False)
    op.create_table('chart_survey_association',
    sa.Column('chart_id', sa.Integer(), nullable=True),
    sa.Column('survey_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chart_id'], ['chart.id'], ),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], )
    )
    op.create_table('criterion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('survey_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_criterion_id'), 'criterion', ['id'], unique=False)
    op.create_index(op.f('ix_criterion_name'), 'criterion', ['name'], unique=False)
    op.create_index(op.f('ix_criterion_survey_id'), 'criterion', ['survey_id'], unique=False)
    op.create_table('survey_user_association',
    sa.Column('survey_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chart1_id', sa.Integer(), nullable=True),
    sa.Column('chart2_id', sa.Integer(), nullable=True),
    sa.Column('survey_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chart1_id'], ['chart.id'], ),
    sa.ForeignKeyConstraint(['chart2_id'], ['chart.id'], ),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_chart1_id'), 'task', ['chart1_id'], unique=False)
    op.create_index(op.f('ix_task_chart2_id'), 'task', ['chart2_id'], unique=False)
    op.create_index(op.f('ix_task_id'), 'task', ['id'], unique=False)
    op.create_index(op.f('ix_task_survey_id'), 'task', ['survey_id'], unique=False)
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('criterion_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['criterion_id'], ['criterion.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_criterion_id'), 'answer', ['criterion_id'], unique=False)
    op.create_index(op.f('ix_answer_id'), 'answer', ['id'], unique=False)
    op.create_index(op.f('ix_answer_task_id'), 'answer', ['task_id'], unique=False)
    op.create_index(op.f('ix_answer_user_id'), 'answer', ['user_id'], unique=False)
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_id'), 'report', ['id'], unique=False)
    op.create_index(op.f('ix_report_task_id'), 'report', ['task_id'], unique=False)
    op.create_index(op.f('ix_report_user_id'), 'report', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_user_id'), table_name='report')
    op.drop_index(op.f('ix_report_task_id'), table_name='report')
    op.drop_index(op.f('ix_report_id'), table_name='report')
    op.drop_table('report')
    op.drop_index(op.f('ix_answer_user_id'), table_name='answer')
    op.drop_index(op.f('ix_answer_task_id'), table_name='answer')
    op.drop_index(op.f('ix_answer_id'), table_name='answer')
    op.drop_index(op.f('ix_answer_criterion_id'), table_name='answer')
    op.drop_table('answer')
    op.drop_index(op.f('ix_task_survey_id'), table_name='task')
    op.drop_index(op.f('ix_task_id'), table_name='task')
    op.drop_index(op.f('ix_task_chart2_id'), table_name='task')
    op.drop_index(op.f('ix_task_chart1_id'), table_name='task')
    op.drop_table('task')
    op.drop_table('survey_user_association')
    op.drop_index(op.f('ix_criterion_survey_id'), table_name='criterion')
    op.drop_index(op.f('ix_criterion_name'), table_name='criterion')
    op.drop_index(op.f('ix_criterion_id'), table_name='criterion')
    op.drop_table('criterion')
    op.drop_table('chart_survey_association')
    op.drop_index(op.f('ix_survey_type'), table_name='survey')
    op.drop_index(op.f('ix_survey_status'), table_name='survey')
    op.drop_index(op.f('ix_survey_researcher_id'), table_name='survey')
    op.drop_index(op.f('ix_survey_name'), table_name='survey')
    op.drop_index(op.f('ix_survey_id'), table_name='survey')
    op.drop_table('survey')
    op.drop_index(op.f('ix_chart_y_axis_title'), table_name='chart')
    op.drop_index(op.f('ix_chart_x_axis_title'), table_name='chart')
    op.drop_index(op.f('ix_chart_type'), table_name='chart')
    op.drop_index(op.f('ix_chart_title'), table_name='chart')
    op.drop_index(op.f('ix_chart_id'), table_name='chart')
    op.drop_index(op.f('ix_chart_description'), table_name='chart')
    op.drop_table('chart')
    # ### end Alembic commands ###
