"""Answer table tweaks

Revision ID: 24678388161b
Revises: f3c92519a99f
Create Date: 2019-06-04 15:26:49.118300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24678388161b'
down_revision = 'f3c92519a99f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('chosen_chart_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_answer_chosen_chart_id'), 'answer', ['chosen_chart_id'], unique=False)
    op.drop_index('ix_answer_criterion_id', table_name='answer')
    op.drop_constraint('answer_criterion_id_fkey', 'answer', type_='foreignkey')
    op.create_foreign_key(None, 'answer', 'chart', ['chosen_chart_id'], ['id'])
    op.drop_column('answer', 'criterion_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('criterion_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.create_foreign_key('answer_criterion_id_fkey', 'answer', 'criterion', ['criterion_id'], ['id'])
    op.create_index('ix_answer_criterion_id', 'answer', ['criterion_id'], unique=False)
    op.drop_index(op.f('ix_answer_chosen_chart_id'), table_name='answer')
    op.drop_column('answer', 'chosen_chart_id')
    # ### end Alembic commands ###
