"""Add is_researcher to user

Revision ID: 498c2b55778d
Revises: 6b7b9069d660
Create Date: 2019-05-22 20:39:28.637202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '498c2b55778d'
down_revision = '6b7b9069d660'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_researcher', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_researcher')
    # ### end Alembic commands ###
