"""Chart - array of chart types

Revision ID: 74787c1d9f64
Revises: 2953caf79f75
Create Date: 2019-06-09 11:55:53.202365

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.db.utils import ArrayOfEnum

# revision identifiers, used by Alembic.
revision = '74787c1d9f64'
down_revision = '2953caf79f75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chart',
                    'type',
                    existing_type=postgresql.ENUM('AREA_PLOT',
                                                  'BAR_PLOT',
                                                  'BOX_PLOT',
                                                  'BUBBLE_CHART',
                                                  'CHART',
                                                  'COLUMN_PLOT',
                                                  'DIAGRAM',
                                                  'DOT_PLOT',
                                                  'LINEAR_PLOT',
                                                  'OTHER_PLOT',
                                                  'PARETO_CHART',
                                                  'PIE_CHART',
                                                  'RADAR_PLOT',
                                                  'SCATTER_PLOT',
                                                  name='charttype'),
                    type_=ArrayOfEnum(
                        sa.Enum('AREA_PLOT',
                                'BAR_PLOT',
                                'BOX_PLOT',
                                'BUBBLE_CHART',
                                'CHART',
                                'COLUMN_PLOT',
                                'DIAGRAM',
                                'DOT_PLOT',
                                'LINEAR_PLOT',
                                'OTHER_PLOT',
                                'PARETO_CHART',
                                'PIE_CHART',
                                'RADAR_PLOT',
                                'SCATTER_PLOT',
                                name='charttype')),
                    postgresql_using='array[type]',
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chart',
                    'type',
                    existing_type=ArrayOfEnum(
                        sa.Enum('AREA_PLOT',
                                'BAR_PLOT',
                                'BOX_PLOT',
                                'BUBBLE_CHART',
                                'CHART',
                                'COLUMN_PLOT',
                                'DIAGRAM',
                                'DOT_PLOT',
                                'LINEAR_PLOT',
                                'OTHER_PLOT',
                                'PARETO_CHART',
                                'PIE_CHART',
                                'RADAR_PLOT',
                                'SCATTER_PLOT',
                                name='charttype')),
                    type_=postgresql.ENUM('AREA_PLOT',
                                          'BAR_PLOT',
                                          'BOX_PLOT',
                                          'BUBBLE_CHART',
                                          'CHART',
                                          'COLUMN_PLOT',
                                          'DIAGRAM',
                                          'DOT_PLOT',
                                          'LINEAR_PLOT',
                                          'OTHER_PLOT',
                                          'PARETO_CHART',
                                          'PIE_CHART',
                                          'RADAR_PLOT',
                                          'SCATTER_PLOT',
                                          name='charttype'),
                    postgresql_using='type[1]',
                    existing_nullable=True)
    # ### end Alembic commands ###
