"""Remove Criterion. Additional columns for ranking

Revision ID: b9c448824b99
Revises: be5f887c6775
Create Date: 2019-06-10 12:31:24.842992

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b9c448824b99'
down_revision = 'be5f887c6775'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_criterion_id', table_name='criterion')
    op.drop_index('ix_criterion_name', table_name='criterion')
    op.drop_index('ix_criterion_survey_id', table_name='criterion')
    op.drop_table('criterion')
    op.add_column('answer',
                  sa.Column('chosen_chart_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_answer_chosen_chart_id'),
                    'answer', ['chosen_chart_id'],
                    unique=False)
    op.drop_index('ix_answer_criterion_id', table_name='answer')
    op.drop_constraint('answer_criterion_id_fkey',
                       'answer',
                       type_='foreignkey')
    op.create_foreign_key(None, 'answer', 'chart', ['chosen_chart_id'], ['id'])
    op.drop_column('answer', 'criterion_id')
    op.add_column('chart_survey_association',
                  sa.Column('mu', sa.Float(), nullable=True))
    op.add_column('chart_survey_association',
                  sa.Column('sigma', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chart_survey_association', 'sigma')
    op.drop_column('chart_survey_association', 'mu')
    op.add_column(
        'answer',
        sa.Column('criterion_id',
                  sa.INTEGER(),
                  autoincrement=False,
                  nullable=True))
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.create_foreign_key('answer_criterion_id_fkey', 'answer', 'criterion',
                          ['criterion_id'], ['id'])
    op.create_index('ix_answer_criterion_id',
                    'answer', ['criterion_id'],
                    unique=False)
    op.drop_index(op.f('ix_answer_chosen_chart_id'), table_name='answer')
    op.drop_column('answer', 'chosen_chart_id')
    op.create_table(
        'criterion',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('name',
                  sa.VARCHAR(length=200),
                  autoincrement=False,
                  nullable=True),
        sa.Column('survey_id',
                  sa.INTEGER(),
                  autoincrement=False,
                  nullable=True),
        sa.ForeignKeyConstraint(['survey_id'], ['survey.id'],
                                name='criterion_survey_id_fkey'),
        sa.PrimaryKeyConstraint('id', name='criterion_pkey'))
    op.create_index('ix_criterion_survey_id',
                    'criterion', ['survey_id'],
                    unique=False)
    op.create_index('ix_criterion_name', 'criterion', ['name'], unique=False)
    op.create_index('ix_criterion_id', 'criterion', ['id'], unique=False)
    # ### end Alembic commands ###
