"""Add dates

Revision ID: be5f887c6775
Revises: 74787c1d9f64
Create Date: 2019-06-09 18:17:06.343109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be5f887c6775'
down_revision = '74787c1d9f64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('chart', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('survey', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('survey', sa.Column('deadline', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'created')
    op.drop_column('survey', 'deadline')
    op.drop_column('survey', 'created')
    op.drop_column('chart', 'created')
    op.drop_column('answer', 'created')
    # ### end Alembic commands ###
