"""File related changes in Chart table

Revision ID: f3c92519a99f
Revises: 498c2b55778d
Create Date: 2019-06-02 03:06:11.131038

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f3c92519a99f'
down_revision = '498c2b55778d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chart', sa.Column('file_ext', sa.VARCHAR(length=10), nullable=True))
    op.add_column('chart', sa.Column('file_hash', sa.VARCHAR(length=64), nullable=True))
    op.alter_column('chart', 'type',
               existing_type=postgresql.ENUM('AREA_GRAPH', 'BAR_GRAPH', 'BOX_PLOT', 'BUBBLE_CHART', 'COLUMN_GRAPH', 'LINE_GRAPH', 'PARETO_CHART', 'PIE_CHART', 'RADAR_PLOT', 'SCATTER_GRAPH', name='charttype'),
               type_=sa.Enum('AREA_PLOT', 'BAR_PLOT', 'BOX_PLOT', 'BUBBLE_CHART', 'CHART', 'COLUMN_PLOT', 'DIAGRAM', 'DOT_PLOT', 'LINEAR_PLOT', 'OTHER_PLOT', 'PARETO_CHART', 'PIE_CHART', 'RADAR_PLOT', 'SCATTER_PLOT', name='charttype'),
               existing_nullable=True)
    op.drop_column('chart', 'filepath')
    op.alter_column('user', 'is_researcher',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_researcher',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('chart', sa.Column('filepath', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.alter_column('chart', 'type',
               existing_type=sa.Enum('AREA_PLOT', 'BAR_PLOT', 'BOX_PLOT', 'BUBBLE_CHART', 'CHART', 'COLUMN_PLOT', 'DIAGRAM', 'DOT_PLOT', 'LINEAR_PLOT', 'OTHER_PLOT', 'PARETO_CHART', 'PIE_CHART', 'RADAR_PLOT', 'SCATTER_PLOT', name='charttype'),
               type_=postgresql.ENUM('AREA_GRAPH', 'BAR_GRAPH', 'BOX_PLOT', 'BUBBLE_CHART', 'COLUMN_GRAPH', 'LINE_GRAPH', 'PARETO_CHART', 'PIE_CHART', 'RADAR_PLOT', 'SCATTER_GRAPH', name='charttype'),
               existing_nullable=True)
    op.drop_column('chart', 'file_hash')
    op.drop_column('chart', 'file_ext')
    # ### end Alembic commands ###
