"""File related changes in Chart table

Revision ID: f3c92519a99f
Revises: 498c2b55778d
Create Date: 2019-06-02 03:06:11.131038

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f3c92519a99f'
down_revision = '498c2b55778d'
branch_labels = None
depends_on = None

old_enum_charttype = sa.Enum('AREA_GRAPH', 'BAR_GRAPH', 'BOX_PLOT', 'BUBBLE_CHART', 'COLUMN_GRAPH', 'LINE_GRAPH',
                             'PARETO_CHART', 'PIE_CHART', 'RADAR_PLOT', 'SCATTER_GRAPH', name='charttype')
new_enum_charttype = sa.Enum('AREA_PLOT', 'BAR_PLOT', 'BOX_PLOT', 'BUBBLE_CHART', 'CHART', 'COLUMN_PLOT', 'DIAGRAM',
                             'DOT_PLOT', 'LINEAR_PLOT', 'OTHER_PLOT', 'PARETO_CHART', 'PIE_CHART', 'RADAR_PLOT',
                             'SCATTER_PLOT', name='charttype')
tmp_enum_charttype = sa.Enum('AREA_PLOT', 'BAR_PLOT', 'BOX_PLOT', 'BUBBLE_CHART', 'CHART', 'COLUMN_PLOT', 'DIAGRAM',
                             'DOT_PLOT', 'LINEAR_PLOT', 'OTHER_PLOT', 'PARETO_CHART', 'PIE_CHART', 'RADAR_PLOT',
                             'SCATTER_PLOT', name='_charttype')
chart_table = sa.sql.table('chart', sa.Column('type', new_enum_charttype, nullable=True))


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chart', sa.Column('file_ext', sa.VARCHAR(length=10), nullable=True))
    op.add_column('chart', sa.Column('file_hash', sa.VARCHAR(length=64), nullable=True))
    tmp_enum_charttype.create(op.get_bind(), checkfirst=False)
    op.execute('ALTER TABLE chart ALTER COLUMN type TYPE _charttype USING type::text::_charttype')
    old_enum_charttype.drop(op.get_bind(), checkfirst=False)
    new_enum_charttype.create(op.get_bind(), checkfirst=False)
    op.execute('ALTER TABLE chart ALTER COLUMN type TYPE charttype USING type::text::charttype')
    tmp_enum_charttype.drop(op.get_bind(), checkfirst=False)
    op.drop_column('chart', 'filepath')
    op.alter_column('user', 'is_researcher',
                    existing_type=sa.BOOLEAN(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_researcher',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    op.add_column('chart', sa.Column('filepath', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.execute(chart_table.update().where(sa.or_(chart_table.c.type == 'AREA_PLOT',
                                                 chart_table.c.type == 'BAR_PLOT',
                                                 chart_table.c.type == 'COLUMN_PLOT',
                                                 chart_table.c.type == 'LINEAR_PLOT',
                                                 chart_table.c.type == 'SCATTER_PLOT',
                                                 chart_table.c.type == 'CHART',
                                                 chart_table.c.type == 'DIAGRAM',
                                                 chart_table.c.type == 'DOT_PLOT',
                                                 chart_table.c.type == 'OTHER_PLOT', ))
               .values(type=None))
    tmp_enum_charttype.create(op.get_bind(), checkfirst=False)
    op.execute('ALTER TABLE chart ALTER COLUMN type TYPE _charttype USING type::text::_charttype')
    new_enum_charttype.drop(op.get_bind(), checkfirst=False)
    old_enum_charttype.create(op.get_bind(), checkfirst=False)
    op.execute('ALTER TABLE chart ALTER COLUMN type TYPE charttype USING type::text::charttype')
    tmp_enum_charttype.drop(op.get_bind(), checkfirst=False)
    op.drop_column('chart', 'file_hash')
    op.drop_column('chart', 'file_ext')
    # ### end Alembic commands ###
